version: "3.9"

services:
  minio:
    container_name: webhook-minio
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
      MINIO_NOTIFY_WEBHOOK_ENABLE: on
      MINIO_NOTIFY_WEBHOOK_ENDPOINT: http://localhost:3000/minio/event
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    network_mode: host
    
  mc:
    container_name: webhook-minio-event-setup
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
        /bin/sh -c "
          sleep 5;
          mc alias set myminio http://localhost:9000 minio miniominio;
          mc mb myminio/mybucket;
          mc event add myminio/mybucket arn:minio:sqs::_:webhook --event put
        "
    network_mode: host
