version: "3"
services:
  # master-slave replication
  master:
    image: redis

  slave:
    deploy:
      replicas: 2
    image: redis
    command: redis-server --slaveof master 6379
    depends_on:
      - master

  # sentinel
  sentinel-1:
    image: redis
    volumes:
      - ./config:/etc/redis-config
    command: redis-sentinel /etc/redis-config/sentinel-1.conf
    depends_on:
      - master

  sentinel-2:
    image: redis
    volumes:
      - ./config:/etc/redis-config
    command: redis-sentinel /etc/redis-config/sentinel-2.conf
    depends_on:
      - master

  sentinel-3:
    image: redis
    volumes:
      - ./config:/etc/redis-config
    command: redis-sentinel /etc/redis-config/sentinel-3.conf
    depends_on:
      - master

  sentinel-4:
    image: redis
    volumes:
      - ./config:/etc/redis-config
    command: redis-sentinel /etc/redis-config/sentinel-4.conf
    depends_on:
      - master
