up:
	@rm -rf ./config
	@mkdir -p ./config
	@cp redis.conf ./config/redis-1.conf
	@cp redis.conf ./config/redis-2.conf
	@cp redis.conf ./config/redis-3.conf
	@cp redis.conf ./config/redis-4.conf
	@cp redis.conf ./config/redis-5.conf
	@cp redis.conf ./config/redis-6.conf
	@docker-compose up -d

down:
	@docker-compose down
