version: "3"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.7
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - "8123:8123"
      - "9000:9000"

  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
      POSTGRES_DB: uptrace
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uptrace -d uptrace"]
      interval: 1s
      timeout: 1s
      retries: 30
    ports:
      - "5432:5432"

  uptrace:
    image: "uptrace/uptrace:1.7.6"
    restart: on-failure
    volumes:
      - ./uptrace.yaml:/etc/uptrace/uptrace.yml
    ports:
      - "14317:14317"
      - "14318:14318"
    depends_on:
      - clickhouse
      - postgres

  # otelcol:
  #   image: otel/opentelemetry-collector-contrib:0.88.0
  #   restart: on-failure
  #   volumes:
  #     - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
  #   ports:
  #     - '4317:4317'
  #     - '4318:4318'
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'
  #   depends_on:
  #     - uptrace
